### ISSUE TITLE
Add shop.exaltedEquiv, shop.alchEquiv, etc.

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#107]
Currently, in order to find items that are priced 3alch against shop.chaosEquiv, clients will need to lookup the rate table:
http://exiletools.com/rates

But maybe we can add this information as fields. The clients will simple have to query against the ff fields:

   shop.exaltedEquiv
   shop.alchemyEquiv
   shop.fusingEquiv

side question: does the field names length matter that much on bandwidth cost? I assume having longer field names makes the resulting json larger which makes the overall http roundtrip slower.

**Comment by trackpete** [comment]
I need to think about this a bit. In general, I would rather this be done via lookup - that data is very easy to derive against chaosEquiv, so any service that wants to calculate against that should be able to store the data (the rates are typically fixed for many months). Since chaosEquiv goes out to three places, it's easy to do the lookup - 3 alch = x chaos = search for chaosEquiv gt x. It seems like an unnecessary field to add because it's so easy to calculate against (and while some bit of bloat is happening right now, I don't want to go willy nilly).

Maybe I can think of another way though.

For bandwidth, right now I'm mostly relying on gzip compression to smooth that stuff out. If you're not using it in your client, you should make sure it's enabled.

Additionally, if you're worried about it, you *can* tell Elastic Search to only return specific fields in the responses. So far I haven't seen things be too terrible though, a lot of latency is in the requests still.

**Comment by trackpete** [comment]
The more I think about this, the more I think it's better done client side. The `chaosEquiv` is intended as a *reference* and is a fixed value, so you can always derive any other currency from it. Keeping it as a fixed value makes easy searching and sorting, but it will never be perfectly accurate.

I will add a new feature to allow tools and indexers to specify their own rates though. 

And I'll see about adding a JSON endpoint somewhere to get the rates programmatically.

**Comment by trackpete** [comment]
Done: 
http://exiletools.com/rates?json

or

http://api.exiletools.com/endpoints/rates?json

**Comment by thirdy** [comment]
Still wish these fields were added.

It's on the same reason as adding the `avg` value for Mods.

But I guess this is just a problem+laziness from me. The way I use exiletools right now is by using the `query-string` syntax; and user input is a string, what I do is just regex-parse:

```
#
# buyout
# for rates, see: http://exiletools.com/rates
#
(([0-9]+)?(\.)?([0-9]{1,2})?)(ch?(aos)?):
  query: shop.chaosEquiv:[* TO $1]
  example:
  - 3ch
  - 10chaos
  - 9.19chaos
  description: |
      Items with less than or equal to the
      specified buyout in Chaos Equivalent.

(([0-9]+)?(\.)?([0-9]{1,2})?)-(([0-9]+)?(\.)?([0-9]{1,2})?)(ch?(aos)?):
  query: shop.chaosEquiv:[$1 TO $2]
  example:
  - 3-5ch
  - 10-20.5chaos
  - 19.19-30chaos

# https://github.com/trackpete/exiletools-indexer/issues/107
#(([0-9]+)?(\.)?([0-9]{1,2})?)(alch?(emy)?):
#  query: shop.chaosEquiv:[$1 TO $2]
  
#(([0-9]+)?(\.)?([0-9]{1,2})?)-(([0-9]+)?(\.)?([0-9]{1,2})?)(alch?(emy)?)    =       buyout_currency=alchemy&buyout_min=$GROUP1&buyout_max=$GROUP2

#(([0-9]+)?(\.)?([0-9]{1,2})?)(fus(ing|e)?)                                  =       buyout_currency=fusing&buyout_max=$GROUP1
#(([0-9]+)?(\.)?([0-9]{1,2})?)-(([0-9]+)?(\.)?([0-9]{1,2})?)(fus(ing|e)?)    =       buyout_currency=fusing&buyout_min=$GROUP1&buyout_max=$GROUP2
#
#(([0-9]+)?(\.)?([0-9]{1,2})?)(ex(alted)?)                                  =       buyout_currency=exalted&buyout_max=$GROUP1
#(([0-9]+)?(\.)?([0-9]{1,2})?)-(([0-9]+)?(\.)?([0-9]{1,2})?)(ex(alted)?)    =       buyout_currency=exalted&buyout_min=$GROUP1&buyout_max=$GROUP2
#
#(([0-9]+)?(\.)?([0-9]{1,2})?)(alt(eration)?)                               =       buyout_currency=alteration&buyout_max=$GROUP1
#(([0-9]+)?(\.)?([0-9]{1,2})?)-(([0-9]+)?(\.)?([0-9]{1,2})?)(alt(eration)?) =       buyout_currency=alteration&buyout_min=$GROUP1&buyout_max=$GROUP2
```

But more over, this is an unwanted-difficulty of the non-AST solution I took. (I didn't have any compiler subjects at school, so I have not much idea AST is actually :D).
